# Generated by Django 3.0.3 on 2020-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gottem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilizador',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='username',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(db_column='Password', max_length=500),
        ),
    ]
