# Generated by Django 3.0.3 on 2020-05-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gottem', '0002_auto_20200423_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='password_reset_url',
            field=models.CharField(blank=True, db_column='Password_reset_url', max_length=500, null=True),
        ),
    ]
