# Generated by Django 3.0.3 on 2020-05-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gottem', '0003_utilizador_password_reset_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='gestão_de_perfilid',
        ),
    ]
